server:
  port: 8999

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-routes
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: user-routes
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: mechanic-routes
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/mechanics/**
        - id: request-routes
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/api/v1/requests/**
        - id: location-routes
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/api/v1/location/**
        - id: notification-routes
          uri: lb://NOTIFICATION-SERVICE
          predicates:
          - Path=/api/v1/notifications/**,/ws/**

jwt:
  secret: ${my.secret.key}