spring:
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          breakdownRequestEvent:com.roadrescue.notification_service.dto.BreakdownRequestEvent,
          mechanicNotificationEvent:com.roadrescue.notification_service.dto.MechanicNotificationEvent,
          mechanicAssignmentEvent:com.roadrescue.notification_service.dto.MechanicAssignmentEvent

    topic:
      breakdown-request-topic: breakdown-requests
      mechanic-notification-topic: mechanic-notifications
      mechanic-assignment-topic: mechanic-assignments

# Server Configuration
server:
  port: 8086

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Logging
logging:
  level:
    com.roadrescue.notification_service: DEBUG
    org.springframework.kafka: INFO
    org.springframework.messaging: DEBUG