spring:
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          breakdownRequestEvent:com.roadrescue.notification_service.dto.BreakdownRequestEvent,
          mechanicNotificationEvent:com.roadrescue.notification_service.dto.MechanicNotificationEvent,
          mechanicAssignmentEvent:com.roadrescue.notification_service.dto.MechanicAssignmentEvent,
          locationUpdateEvent:com.roadrescue.notification_service.dto.LocationUpdateEvent,
          serviceCompletionEvent:com.roadrescue.notification_service.dto.ServiceCompletionEvent,
          paymentEvent:com.roadrescue.notification_service.dto.PaymentEvent,
          reviewEvent:com.roadrescue.notification_service.dto.ReviewEvent
    topic:
      breakdown-request-topic: breakdown-requests
      mechanic-notification-topic: mechanic-notifications
      mechanic-assignment-topic: mechanic-assignments
      location-updates-topic: location-updates
      service-completion-topic: service-completion
      payments-topic: payments
      reviews-topic: reviews

server:
  port: 8086

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.roadrescue.notification_service: DEBUG
