spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/roadrescue_request_db
    username: hemant_user
    password: roadrescuePass@48
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true
  kafka:
    bootstrap-servers: localhost:9093

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: breakdownRequestEvent:com.roadrescue.request_service.dto.BreakdownRequestEvent
      acks: all
      retries: 3
    topic:
      breakdown-request-topic: breakdown-requests

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/